Create snip-55.mp
starknet-io/SNIPs pull request #113
Opened 2024-10-24 13:49 UTC by ClementWalter

Add SNIP-55 similar to ERC-55

2024-10-24 14:04 UTC, Eikix reviewed
Please add missing paragraphs:
1/ abstract
2/ backward compatibility considerations? will this snip break tools
3/ security considerations
4/ copyright waiver

2024-10-27 08:52 UTC, leo-starkware commented
Could you also add a "security considerations" section? (Even if there are no security issues involved)

2024-10-27 08:53 UTC, leo-starkware commented on SNIPS/snip-55.md
> +def checksum_encode(addr: int): # Takes a 32-byte binary address as input
Add the output type
```
def checksum_encode(addr: int) -> str:
```

2024-10-27 08:53 UTC, leo-starkware commented on SNIPS/snip-55.md
> +In English, convert the address to hex, but if the `i`th digit is a letter (ie. it's one of `abcdef`) print it in uppercase if the `4*i`th bit of the hash of the lowercase hexadecimal address is 1 ot
ie. -> i.e.

"of the hash" -> "of the keccak hash"

2024-10-30 06:33 UTC, leo-starkware requested changes

2024-10-30 06:33 UTC, leo-starkware commented on SNIPS/snip-55.md
> +def checksum_encode(addr: int): -> str # Takes a 32-byte binary address as input
def checksum_encode(addr: int) -> str: (colons after the return type)

2024-10-30 06:33 UTC, leo-starkware commented on SNIPS/snip-55.md
> +In English, convert the address to hex, but if the `i`th digit is a letter (ie. it's one of `abcdef`) print it in uppercase if the `4*i`th bit of the keccak hash of the lowercase hexadecimal address
in the parentheses, "ie." should be "i.e."

2024-11-12 08:14 UTC, leo-starkware reviewed
Looks good. Can you change the snip number to 23? This is the current consecutive number policy (discussion on possible modifcation is ongoing [here](https://community.starknet.io/t/snip-numbering-policy-and-draft-snips/115023)).

2024-12-09 12:17 UTC, leo-starkware approved these changes

2024-12-09 12:17 UTC, merged